using System;
using System.Configuration;
using System.Data.SqlClient;
using System.Text;
using System.Web;                                                           

public partial class GenerateSqlScript : System.Web.UI.Page
{
         
    protected void btnGenerateScript_Click(object sender, EventArgs e)
    {
        try
        {
            string connStr = ConfigurationManager.ConnectionStrings["dbcon"].ConnectionString;

            StringBuilder script = new StringBuilder();

            // Add header comments
            script.AppendLine("-- =============================================");
            script.AppendLine("-- SQL Insert Script for qrcodemaster");
            script.AppendLine("-- Generated by: GenerateSqlScript.aspx page");
            script.AppendLine("-- Date & Time: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            script.AppendLine("-- =============================================");
            script.AppendLine();
           
            using (SqlConnection con = new SqlConnection(connStr))
            {
                string query = "SELECT [qrvalue], [qrtext], [qruse] " +
                               "FROM [handloom_Odisha].[dbo].[qrcodemaster_1] ORDER BY srno";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    con.Open();
                    using (SqlDataReader dr = cmd.ExecuteReader())
                    {
                        int serialNo = 1; // Start serial number from 1

                        while (dr.Read())
                        {
                            string srno = serialNo.ToString("D5"); // 00001, 00002, ...

                            string qrvalue = dr["qrvalue"] != DBNull.Value ? "'" + dr["qrvalue"].ToString().Replace("'", "''") + "'" : "NULL";
                            string qrtext = dr["qrtext"] != DBNull.Value ? "'" + dr["qrtext"].ToString().Replace("'", "''") + "'" : "NULL";
                            string qruse = dr["qruse"] != DBNull.Value ? "'" + dr["qruse"].ToString().Replace("'", "''") + "'" : "NULL";

                            string createddate = "GETDATE()";
                            string updatedate = "GETDATE()";

                            string insert = string.Format(
                                "INSERT INTO qrcodemaster (srno, qrvalue, qrtext, qruse, createddate, updatedate) " +
                                "VALUES ('{0}', {1}, {2}, {3}, {4}, {5});",
                                srno, qrvalue, qrtext, qruse, createddate, updatedate
                            );

                            script.AppendLine(insert);
                            serialNo++;
                        }
                    }
                }
            }

            // Download SQL file
            string fileName = "qrcodemaster_InsertScript_" + DateTime.Now.ToString("yyyyMMddHHmmss") + ".sql";

            Response.Clear();
            Response.ContentType = "application/sql";
            Response.AddHeader("Content-Disposition", "attachment;filename=" + fileName);
            Response.Write(script.ToString());
            Response.Flush();
            HttpContext.Current.ApplicationInstance.CompleteRequest();

            // Display success message (note: may not show if download blocks postback)
            lblMessage.Text = "✅ SQL script generated successfully!";
        }
        catch (Exception ex)
        {
            lblMessage.ForeColor = System.Drawing.Color.Red;
            lblMessage.Text = "❌ Error: " + ex.Message;
        }
    }
}
